/**
 * MiningPlatform
 * Author: Abia Nugrahanto
 * Copyright (c) 2026 Abia Nugrahanto. All rights reserved.
 */

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions.
