# MiningPlatform
# Author: Abia Nugrahanto
# Copyright (c) 2026 Abia Nugrahanto. All rights reserved.

packages:
  - apps/*
  - packages/*
overrides:
  framer-motion@12.0.0>motion-dom: 12.0.0
  framer-motion@12.0.0>motion-utils: 12.0.0
  motion-dom@12.0.0>motion-utils: 12.0.0
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
